# -*- coding: utf-8 -*-
"""نسخة من project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qm7L8wjA9qLAeDPAMRoLM4tUq_MiNjFk
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = "/content/drive/MyDrive/DF_Project/Final_Dataset2.xlsx"

df = pd.read_excel(file_path)

print("Shape:", df.shape)
df.head()

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

if 'TimeStamp' in df.columns:
    df = df.drop(columns=['TimeStamp',"AgeGroup","Gender","MaritalStatus","EmploymentStatus"]) # drop TimeStamp since it's not biometric

# check missing values
print("Missing values in each column:")
print(df.isna().sum())
df = df.fillna(df.mean(numeric_only=True))

y = df['DB_Case']  # Goal
X = df.drop(columns=['DB_Case'])

# convert the goal to numbers 

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_enc = le.fit_transform(y)

num_classes = len(np.unique(y_enc))
num_classes

# split data to training & testing
X_train, X_test, y_train, y_test = train_test_split(X, y_enc, test_size=0.2, random_state=42, stratify=y_enc)

# scalling ( important in model )
from sklearn.preprocessing import StandardScaler
import joblib  # to save scale

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

joblib.dump(scaler, 'scaler.pkl')

# calculate class weight
from sklearn.utils.class_weight import compute_class_weight

classes = np.unique(y_train)
class_weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)
class_weight_dict = {c: w for c, w in zip(classes, class_weights)}

class_weight_dict

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout ,BatchNormalization

def build_model(input_dim,num_classes,dropout_rate=0.2):
    model = Sequential([
        Dense(128, activation='relu', input_dim=input_dim),
        BatchNormalization(),
        Dropout(dropout_rate),

        Dense(64, activation='relu'),
        BatchNormalization(),
        Dropout(dropout_rate),

        Dense(32, activation='relu'),
        Dropout(dropout_rate),

        Dense(num_classes, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model


model = build_model(input_dim=X_train_scaled.shape[1], num_classes=num_classes,dropout_rate=0.25)
model.summary()

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

es = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True, verbose=1)
mc = ModelCheckpoint('best_biometric_model.h5', monitor='val_loss', save_best_only=True, verbose=1)
rlr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=7, min_lr=1e-6, verbose=1)

# start training
history = model.fit(
    X_train_scaled, y_train,
    validation_split=0.15,
    epochs=200,
    batch_size=16,
    class_weight=class_weight_dict,
    callbacks=[es, mc, rlr],
    verbose=2
)

# evaluate and print Accuracy
test_loss, test_acc = model.evaluate(X_test_scaled, y_test, verbose=0)
print(f"Test Accuracy: {test_acc:.4f}  |  Loss: {test_loss:.4f}")

# confusion matrix
y_pred = model.predict(X_test_scaled)
y_pred = y_pred.argmax(axis=1)

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(12,8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Test Loss')
plt.legend(); plt.title('Loss')

plt.subplot(1,2,2)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Test Accuracy')
plt.legend(); plt.title('Accuracy')

plt.show()

model.save('/content/drive/MyDrive/file/MyDrivemy_model.keras')